### ISSUE TITLE
The Ironmon Data website is offline

### ISSUE THREAD

**Issue by UTDZac** [MynSzx/mynszx.github.io#3]
The published site `https://mynszx.github.io/ironmondata` appears to be offline as of recently. I believe this is due to the build check failing, but I don't know too much about GitHub itself to know why it broke or what happened here.

Just wanted to open an issue to say that the site has been down all of yesterday.

![image](https://user-images.githubusercontent.com/4258818/216131407-5d704d5a-9818-4f76-b30e-35d3486bf64b.png)

**Comment by MynSzx** [comment]
Fixed!
